# https://www.reddit.com/r/youtubedl/comments/t65ahf/comment/hz9m05d/
# https://www.perplexity.ai/search/give-me-the-instructions-to-ge-wTtTqzy6RFWGuz8p__qagg#1

-x --audio-format m4a
# SoundCloud+ OAuth 2 Token
--add-header "Authorization:2-308324-3994757-vSsFuCF7HiN75O9G"
--audio-quality 0
--add-metadata
--embed-thumbnail
--convert-thumbnails png
--ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
