# https://www.reddit.com/r/youtubedl/comments/t65ahf/comment/hz9m05d/
-t mp3
--audio-quality 0
--add-metadata
--embed-thumbnail
--convert-thumbnails png
--ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
