# https://www.reddit.com/r/youtubedl/comments/t65ahf/comment/hz9m05d/
# https://www.perplexity.ai/search/give-me-the-instructions-to-ge-wTtTqzy6RFWGuz8p__qagg#1

# -x --audio-format m4a
# # SoundCloud+ OAuth 2 Token
# --add-header "Authorization:redacted"
# --audio-quality 0
# --add-metadata
# --embed-thumbnail
# --convert-thumbnails png
# --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

-x --audio-format m4a
--audio-quality 0
--add-metadata
--embed-thumbnail
--convert-thumbnails jpg
# --ppa "ThumbnailsConvertor+ffmpeg_i:-vf crop=ih:ih"
--ppa "ThumbnailsConvertor:-vf crop=ih:ih"
